project:
  type: website
  output-dir: _site

# Add variables here so they can be accessed across the project
metadata:
  # --- Class Information ---
  class_name: "Template Course Title"
  course_code: "TMPL101"
  period: "Template Semester Year"
  # --- Repository and Drive URLs ---
  repository_url: "https://github.com/your-organization/your-repo-template"
  class_drive_url: "https://drive.google.com/drive/folders/your_google_drive_id"
  github_org_url: "https://github.com/your-organization"
  # --- Instructor Information ---
  instructor_name: "[Your Name]"
  instructor_email: "your.email@example.edu"
  office_hours: "By appointment"
  # --- Course Specific Links ---
  syllabus_url: "syllabus.qmd"
  announcements_url: "https://your-lms.com/courses/TMPL101/announcements"

website:
  title: "{{< meta class_name >}} ({{< meta course_code >}}) - {{< meta period >}}"

  navbar:
    left:
      - href: index.qmd
        text: Class Notes
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
      - text: "Appendices"
        menu:
          - text: "A: Getting Started"
            href: a_intro_appendix/00_index.qmd
          - text: "B: Coming Soon..."
            href: "#"
          - text: "C: Quarto Crash Course"
            href: c_quarto_appendix/00_index.qmd
    right:
      - icon: github
        href: "{{< meta repository_url >}}"
        aria-label: GitHub Repository
      - icon: google
        href: "{{< meta class_drive_url >}}"
        text: Drive
        aria-label: Google Drive for Class Files

  page-footer:
    left: "Copyright &copy; {{< meta class_name >}}, {{< meta period >}}"
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: cosmo
    css: 
      - styles/main.css
      - styles/themes/evangelion.css
    toc: true
    code-fold: true 
    code-summary: "Show/Hide Code"
    include-after-body: components/accessibility-auto.html 