name = "Evangelion"
license = "MIT"
licenselink = "https://github.com/license"
description = "A dark educational theme inspired by Evangelion"
homepage = "https://github.com/class-template"
tags = ["education", "dark", "accessibility", "responsive"]
features = ["accessibility", "responsive", "dark-mode"]
min_version = "0.55.0"

[author]
  name = "Class Template Framework"
  homepage = "https://github.com/class-template" 