# Site Configuration - Visual & UX Preferences
# Human-editable file for per-class visual and experience options
# Separate from dna.yml (framework switches) and course.yml (metadata)
# THIS FILE CONTAINS ALL RENDERING PREFERENCES - SELF-CONTAINED

# Theme selection (rendering preference)
theme:
  name: "evangelion"
  path: "framework_code/themes"

# Accessibility options
accessibility:
  default_font: "normal"  # normal | opendyslexic
  high_contrast: false
  reduced_motion: false

# Navigation preferences  
navigation:
  sidebar_style: "tree"   # tree | flat
  show_breadcrumbs: true
  mini_toc: true
  prev_next_arrows: true

# Theme customization
appearance:
  layout: "sidebar"       # sidebar | topnav
  color_scheme: "auto"    # auto | light | dark
  code_highlighting: "github"

# Content display
content:
  show_difficulty_badges: true
  show_estimated_time: true
  homework_highlight: true
  student_solutions_visible: false

# Hugo configuration - all rendering settings
hugo:
  content_sources:
    - "class_notes"
    - "framework_tutorials"
    - "framework_documentation"
  homepage_source: "home.md"
  output_dir: "framework_code/hugo_generated"
  theme_path: "framework_code/themes"
  assets_path: "framework_code/assets"
  search_mode: "simple"

# Advanced build options
build:
  auto_index_generation: true
  strict_validation: false
  include_draft_content: false 