name = "Test Theme"
license = "MIT"
licenselink = "https://github.com/license"
description = "A test theme for validating framework theme separation (Orange/Blue/Pink colors)"
homepage = "https://github.com/class-template"
tags = ["education", "test", "accessibility", "responsive"]
features = ["accessibility", "responsive", "dark-mode"]
min_version = "0.55.0"

[author]
  name = "Class Template Framework"
  homepage = "https://github.com/class-template" 